/**
 * Created by Cral-Gates on 2017/6/25.
 */
'use strict';

export const LOGIN_PERFORM_ACTION = 'LOGIN_PERFORM_ACTION';
export const LOGIN_SUCCESS_ACTION = 'LOGIN_SUCCESS_ACTION';
export const LOGIN_ERROR_ACTION = 'LOGIN_ERROR_ACTION';

export const PERFORM_REGISTER_ACTION = 'PERFORM_REGISTER_ACTION'; //用户注册