/**
 * Created by Cral-Gates on 2017/6/25.
 */
'use strict';
/*
 * 登录
 * */
export const LOGIN_PERFORM_ACTION = 'LOGIN_PERFORM_ACTION';
export const LOGIN_SUCCESS_ACTION = 'LOGIN_SUCCESS_ACTION';
export const LOGIN_ERROR_ACTION = 'LOGIN_ERROR_ACTION';
/*
 * 注册
 * */
export const REGISTER_PERFORM_ACTION = 'PERFORM_REGISTER_ACTION';
export const REGISTER_SUCCESS_ACTION = 'PERFORM_REGISTER_ACTION';
export const REGISTER_ERROR_ACTION = 'PERFORM_REGISTER_ACTION';